"""empty message

Revision ID: c945ca947c9a
Revises: 5ad1deaab3b4
Create Date: 2020-01-24 20:18:06.453200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c945ca947c9a'
down_revision = '5ad1deaab3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('likers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likers',
    sa.Column('liker_id', sa.INTEGER(), nullable=True),
    sa.Column('liked_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['liked_id'], [u'post.id'], ),
    sa.ForeignKeyConstraint(['liker_id'], [u'user.id'], )
    )
    op.drop_table('post_like')
    # ### end Alembic commands ###
